
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Attiq Malik
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Teacher
     */
    public Admin() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTN_ADMIN_LOGIN = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();
        lbpass = new javax.swing.JLabel();
        lbUsername = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lbinfo = new javax.swing.JLabel();
        ADMIN_EXIT = new javax.swing.JButton();
        LB_BACKGROUND = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Teacher");
        setUndecorated(true);
        getContentPane().setLayout(null);

        BTN_ADMIN_LOGIN.setBackground(new java.awt.Color(102, 102, 255));
        BTN_ADMIN_LOGIN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTN_ADMIN_LOGIN.setForeground(new java.awt.Color(255, 255, 255));
        BTN_ADMIN_LOGIN.setText("Login");
        BTN_ADMIN_LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ADMIN_LOGINActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_ADMIN_LOGIN);
        BTN_ADMIN_LOGIN.setBounds(280, 390, 189, 40);

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        getContentPane().add(txtPass);
        txtPass.setBounds(300, 320, 160, 30);

        lbpass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbpass.setForeground(new java.awt.Color(255, 255, 255));
        lbpass.setText("Password");
        getContentPane().add(lbpass);
        lbpass.setBounds(180, 320, 80, 20);

        lbUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbUsername.setForeground(new java.awt.Color(255, 255, 255));
        lbUsername.setText("User_Name");
        getContentPane().add(lbUsername);
        lbUsername.setBounds(180, 265, 100, 20);

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUserName);
        txtUserName.setBounds(300, 270, 160, 30);

        lbinfo.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        lbinfo.setForeground(new java.awt.Color(255, 255, 255));
        lbinfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbinfo.setText("Login your Account");
        getContentPane().add(lbinfo);
        lbinfo.setBounds(138, 187, 490, 50);

        ADMIN_EXIT.setBackground(new java.awt.Color(102, 102, 255));
        ADMIN_EXIT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ADMIN_EXIT.setForeground(new java.awt.Color(255, 255, 255));
        ADMIN_EXIT.setText("BACK");
        ADMIN_EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADMIN_EXITActionPerformed(evt);
            }
        });
        getContentPane().add(ADMIN_EXIT);
        ADMIN_EXIT.setBounds(650, 540, 90, 40);

        LB_BACKGROUND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railway pic.jpg"))); // NOI18N
        getContentPane().add(LB_BACKGROUND);
        LB_BACKGROUND.setBounds(-30, -60, 790, 710);

        setSize(new java.awt.Dimension(759, 674));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed

       
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void BTN_ADMIN_LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ADMIN_LOGINActionPerformed

       
     Checking_Login test;
 
        test = new Checking_Login(txtUserName.getText(),txtPass.getText());
        try {
            //System.out.println(txtUserName.getText());
            //System.out.println(txtPass.getText());
            if(test.check()==1)
            {
                ADMIN_PANEL obj=new ADMIN_PANEL();
                this.dispose();
                obj.setVisible(true);
            }  } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
     
          
    }//GEN-LAST:event_BTN_ADMIN_LOGINActionPerformed

    private void ADMIN_EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADMIN_EXITActionPerformed
        // TODO add your handling code here:
       
         this.dispose();
         Selection_Module back= new Selection_Module();
         back.setVisible(true);
         
        
        
    }//GEN-LAST:event_ADMIN_EXITActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADMIN_EXIT;
    private javax.swing.JButton BTN_ADMIN_LOGIN;
    private javax.swing.JLabel LB_BACKGROUND;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JLabel lbinfo;
    private javax.swing.JLabel lbpass;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
