
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

public class Booking extends javax.swing.JFrame {

   private int rightAns=0;
  
   private int display=0;

  
        
    public Booking() {
       
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        {
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_CLASS_GROUP = new javax.swing.ButtonGroup();
        LB_booking = new javax.swing.JLabel();
        LB_ARRIVAL = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        LB_TRAIN_NAME = new javax.swing.JLabel();
        TXT_TRAIN_NAME = new javax.swing.JTextField();
        LB_DEPARTURE = new javax.swing.JLabel();
        LB_TRAIN_ID = new javax.swing.JLabel();
        TXT_TRAIN_ID = new javax.swing.JTextField();
        LB_CLASS = new javax.swing.JLabel();
        RD_CLASS_BUSINESS = new javax.swing.JRadioButton();
        RD_CLASS_ECONOMY = new javax.swing.JRadioButton();
        RD_CLASS_EXCUTIVE = new javax.swing.JRadioButton();
        jComboBox_ARRIVAL = new javax.swing.JComboBox<>();
        jComboBox_DEPARTURE1 = new javax.swing.JComboBox<>();
        TXT_RENT = new javax.swing.JTextField();
        LB_RENT = new javax.swing.JLabel();
        TXT_DATE = new javax.swing.JTextField();
        LB_DATE = new javax.swing.JLabel();
        find = new javax.swing.JButton();
        LB_USER_Name = new javax.swing.JLabel();
        BTN_DONE_BOOKING1 = new javax.swing.JButton();
        LB_BACKGROUND_PIC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quiz");
        setUndecorated(true);
        getContentPane().setLayout(null);

        LB_booking.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        LB_booking.setForeground(new java.awt.Color(255, 255, 255));
        LB_booking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LB_booking.setText("  Booking");
        getContentPane().add(LB_booking);
        LB_booking.setBounds(280, 40, 360, 100);

        LB_ARRIVAL.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LB_ARRIVAL.setForeground(new java.awt.Color(255, 255, 255));
        LB_ARRIVAL.setText("ARRIVAL");
        getContentPane().add(LB_ARRIVAL);
        LB_ARRIVAL.setBounds(20, 420, 110, 30);

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username);
        username.setBounds(170, 250, 130, 30);

        LB_TRAIN_NAME.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LB_TRAIN_NAME.setForeground(new java.awt.Color(255, 255, 255));
        LB_TRAIN_NAME.setText("Train_Name");
        getContentPane().add(LB_TRAIN_NAME);
        LB_TRAIN_NAME.setBounds(30, 290, 120, 30);
        getContentPane().add(TXT_TRAIN_NAME);
        TXT_TRAIN_NAME.setBounds(170, 290, 130, 30);

        LB_DEPARTURE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LB_DEPARTURE.setForeground(new java.awt.Color(255, 255, 255));
        LB_DEPARTURE.setText("DEPARTURE");
        getContentPane().add(LB_DEPARTURE);
        LB_DEPARTURE.setBounds(20, 380, 110, 30);

        LB_TRAIN_ID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LB_TRAIN_ID.setForeground(new java.awt.Color(255, 255, 255));
        LB_TRAIN_ID.setText("TRAIN_ID");
        getContentPane().add(LB_TRAIN_ID);
        LB_TRAIN_ID.setBounds(30, 330, 110, 30);
        getContentPane().add(TXT_TRAIN_ID);
        TXT_TRAIN_ID.setBounds(170, 330, 130, 30);

        LB_CLASS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LB_CLASS.setForeground(new java.awt.Color(255, 255, 255));
        LB_CLASS.setText("CLASS");
        getContentPane().add(LB_CLASS);
        LB_CLASS.setBounds(30, 470, 110, 30);

        button_CLASS_GROUP.add(RD_CLASS_BUSINESS);
        RD_CLASS_BUSINESS.setText("Business Class");
        RD_CLASS_BUSINESS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RD_CLASS_BUSINESSActionPerformed(evt);
            }
        });
        getContentPane().add(RD_CLASS_BUSINESS);
        RD_CLASS_BUSINESS.setBounds(170, 470, 120, 23);

        button_CLASS_GROUP.add(RD_CLASS_ECONOMY);
        RD_CLASS_ECONOMY.setText("Economy");
        RD_CLASS_ECONOMY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RD_CLASS_ECONOMYActionPerformed(evt);
            }
        });
        getContentPane().add(RD_CLASS_ECONOMY);
        RD_CLASS_ECONOMY.setBounds(323, 473, 110, 20);

        button_CLASS_GROUP.add(RD_CLASS_EXCUTIVE);
        RD_CLASS_EXCUTIVE.setText("Excutive");
        RD_CLASS_EXCUTIVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RD_CLASS_EXCUTIVEActionPerformed(evt);
            }
        });
        getContentPane().add(RD_CLASS_EXCUTIVE);
        RD_CLASS_EXCUTIVE.setBounds(470, 470, 100, 23);

        jComboBox_ARRIVAL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_ARRIVAL);
        jComboBox_ARRIVAL.setBounds(170, 420, 130, 30);

        jComboBox_DEPARTURE1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_DEPARTURE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_DEPARTURE1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_DEPARTURE1);
        jComboBox_DEPARTURE1.setBounds(170, 380, 130, 30);
        getContentPane().add(TXT_RENT);
        TXT_RENT.setBounds(170, 530, 130, 30);

        LB_RENT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LB_RENT.setForeground(new java.awt.Color(255, 255, 255));
        LB_RENT.setText("RENT");
        getContentPane().add(LB_RENT);
        LB_RENT.setBounds(20, 530, 110, 30);
        getContentPane().add(TXT_DATE);
        TXT_DATE.setBounds(170, 580, 130, 30);

        LB_DATE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LB_DATE.setForeground(new java.awt.Color(255, 255, 255));
        LB_DATE.setText("DATE");
        getContentPane().add(LB_DATE);
        LB_DATE.setBounds(20, 580, 110, 30);

        find.setBackground(new java.awt.Color(102, 102, 255));
        find.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        find.setForeground(new java.awt.Color(255, 255, 255));
        find.setText("Find Trains");
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });
        getContentPane().add(find);
        find.setBounds(470, 590, 110, 50);

        LB_USER_Name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LB_USER_Name.setForeground(new java.awt.Color(255, 255, 255));
        LB_USER_Name.setText("User_Name");
        getContentPane().add(LB_USER_Name);
        LB_USER_Name.setBounds(30, 250, 110, 30);

        BTN_DONE_BOOKING1.setBackground(new java.awt.Color(102, 102, 255));
        BTN_DONE_BOOKING1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_DONE_BOOKING1.setForeground(new java.awt.Color(255, 255, 255));
        BTN_DONE_BOOKING1.setText("Submit");
        BTN_DONE_BOOKING1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DONE_BOOKING1ActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_DONE_BOOKING1);
        BTN_DONE_BOOKING1.setBounds(610, 590, 140, 50);

        LB_BACKGROUND_PIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booking.jpg"))); // NOI18N
        getContentPane().add(LB_BACKGROUND_PIC);
        LB_BACKGROUND_PIC.setBounds(0, 0, 750, 650);

        setSize(new java.awt.Dimension(919, 643));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RD_CLASS_BUSINESSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RD_CLASS_BUSINESSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RD_CLASS_BUSINESSActionPerformed

    private void RD_CLASS_EXCUTIVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RD_CLASS_EXCUTIVEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RD_CLASS_EXCUTIVEActionPerformed

    private void jComboBox_DEPARTURE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_DEPARTURE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_DEPARTURE1ActionPerformed

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
  String a=null;
        String sql="Select * from Recent";
           Connectivity c=new  Connectivity();
           ResultSet r= c.getRs(sql);
       try {
           while(r.next())
               a= r.getString(1) ;
       } catch (SQLException ex) {
           Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
       }
        username.setText(a);
        
        

    }//GEN-LAST:event_findActionPerformed

    private void BTN_DONE_BOOKING1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DONE_BOOKING1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_DONE_BOOKING1ActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_usernameActionPerformed

    private void RD_CLASS_ECONOMYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RD_CLASS_ECONOMYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RD_CLASS_ECONOMYActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_DONE_BOOKING1;
    private javax.swing.JLabel LB_ARRIVAL;
    private javax.swing.JLabel LB_BACKGROUND_PIC;
    private javax.swing.JLabel LB_CLASS;
    private javax.swing.JLabel LB_DATE;
    private javax.swing.JLabel LB_DEPARTURE;
    private javax.swing.JLabel LB_RENT;
    private javax.swing.JLabel LB_TRAIN_ID;
    private javax.swing.JLabel LB_TRAIN_NAME;
    private javax.swing.JLabel LB_USER_Name;
    private javax.swing.JLabel LB_booking;
    private javax.swing.JRadioButton RD_CLASS_BUSINESS;
    private javax.swing.JRadioButton RD_CLASS_ECONOMY;
    private javax.swing.JRadioButton RD_CLASS_EXCUTIVE;
    private javax.swing.JTextField TXT_DATE;
    private javax.swing.JTextField TXT_RENT;
    private javax.swing.JTextField TXT_TRAIN_ID;
    private javax.swing.JTextField TXT_TRAIN_NAME;
    private javax.swing.ButtonGroup button_CLASS_GROUP;
    private javax.swing.JButton find;
    private javax.swing.JComboBox<String> jComboBox_ARRIVAL;
    private javax.swing.JComboBox<String> jComboBox_DEPARTURE1;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
