
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Candidate
     */
    public Registration() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbinfo = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        rName = new javax.swing.JTextField();
        lbID = new javax.swing.JLabel();
        BTN_register_save = new javax.swing.JButton();
        lbName1 = new javax.swing.JLabel();
        ridcard = new javax.swing.JTextField();
        lbName2 = new javax.swing.JLabel();
        rphone = new javax.swing.JTextField();
        lbName3 = new javax.swing.JLabel();
        rid = new javax.swing.JTextField();
        STANDARD_USER_BACK = new javax.swing.JButton();
        lbName4 = new javax.swing.JLabel();
        raddress = new javax.swing.JTextField();
        rpass = new javax.swing.JPasswordField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 10, 9));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(null);

        lbinfo.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        lbinfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbinfo.setText("Enter Your Information");
        getContentPane().add(lbinfo);
        lbinfo.setBounds(70, 70, 450, 90);

        lbName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbName.setText("UserName");
        getContentPane().add(lbName);
        lbName.setBounds(40, 170, 100, 34);

        rName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rNameActionPerformed(evt);
            }
        });
        getContentPane().add(rName);
        rName.setBounds(190, 170, 235, 34);

        lbID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbID.setText("Password");
        getContentPane().add(lbID);
        lbID.setBounds(40, 230, 110, 35);

        BTN_register_save.setBackground(new java.awt.Color(102, 102, 255));
        BTN_register_save.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BTN_register_save.setForeground(new java.awt.Color(255, 255, 255));
        BTN_register_save.setText("save");
        BTN_register_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_register_saveActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_register_save);
        BTN_register_save.setBounds(490, 490, 220, 50);

        lbName1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbName1.setText("id_card");
        getContentPane().add(lbName1);
        lbName1.setBounds(40, 290, 100, 34);
        getContentPane().add(ridcard);
        ridcard.setBounds(190, 290, 235, 34);

        lbName2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbName2.setText("Phone");
        getContentPane().add(lbName2);
        lbName2.setBounds(40, 340, 100, 34);
        getContentPane().add(rphone);
        rphone.setBounds(190, 340, 235, 34);

        lbName3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbName3.setText("User_id");
        getContentPane().add(lbName3);
        lbName3.setBounds(40, 400, 100, 34);
        getContentPane().add(rid);
        rid.setBounds(195, 390, 230, 34);

        STANDARD_USER_BACK.setBackground(new java.awt.Color(102, 102, 255));
        STANDARD_USER_BACK.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        STANDARD_USER_BACK.setForeground(new java.awt.Color(255, 255, 255));
        STANDARD_USER_BACK.setText("BACK");
        STANDARD_USER_BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STANDARD_USER_BACKActionPerformed(evt);
            }
        });
        getContentPane().add(STANDARD_USER_BACK);
        STANDARD_USER_BACK.setBounds(10, 490, 230, 50);

        lbName4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbName4.setText("address");
        getContentPane().add(lbName4);
        lbName4.setBounds(50, 440, 100, 34);

        raddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raddressActionPerformed(evt);
            }
        });
        getContentPane().add(raddress);
        raddress.setBounds(195, 440, 240, 34);

        rpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpassActionPerformed(evt);
            }
        });
        getContentPane().add(rpass);
        rpass.setBounds(190, 230, 230, 40);

        background.setBackground(new java.awt.Color(0, 0, 0));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Registrations.jpg"))); // NOI18N
        background.setText("Registration");
        getContentPane().add(background);
        background.setBounds(0, 0, 720, 550);

        setSize(new java.awt.Dimension(721, 545));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_register_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_register_saveActionPerformed
        // TODO add your handling code here:
        
        CLASS_STANDARD_USER check=new CLASS_STANDARD_USER(rName.getText(),rpass.getText(),rid.getText(),rphone.getText(),ridcard.getText(),raddress.getText());
       
        try {
           int  x = check.InsertStatement();
           if(x>0){
                
                JOptionPane.showMessageDialog(null,"Registerd ");
                this.dispose();
                new   Standard_User().setVisible(true);
            }
            else {
                JOptionPane.showMessageDialog(null,"Not Register");
            }
           
           
        } catch (SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            
        
        
        
       
        
        
        
        
        
    }//GEN-LAST:event_BTN_register_saveActionPerformed

    private void STANDARD_USER_BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STANDARD_USER_BACKActionPerformed
        // TODO add your handling code here:

        this.dispose();
        Standard_User m=new Standard_User();
        m.setVisible(true);
    }//GEN-LAST:event_STANDARD_USER_BACKActionPerformed

    private void rNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rNameActionPerformed

    private void raddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raddressActionPerformed

    private void rpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Standard_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Standard_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Standard_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Standard_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Standard_User().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_register_save;
    private javax.swing.JButton STANDARD_USER_BACK;
    private javax.swing.JLabel background;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbName1;
    private javax.swing.JLabel lbName2;
    private javax.swing.JLabel lbName3;
    private javax.swing.JLabel lbName4;
    private javax.swing.JLabel lbinfo;
    private javax.swing.JTextField rName;
    private javax.swing.JTextField raddress;
    private javax.swing.JTextField rid;
    private javax.swing.JTextField ridcard;
    private javax.swing.JPasswordField rpass;
    private javax.swing.JTextField rphone;
    // End of variables declaration//GEN-END:variables
}
