
import java.awt.Color;
import javax.swing.JOptionPane;




public class Selection_Module extends javax.swing.JFrame {

    /**
     * Creates new form Module
     */
    public Selection_Module() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        BTN_STANDARD_USER = new javax.swing.JButton();
        BTN_ADMIN_MOD = new javax.swing.JButton();
        BTN_DETAIL_MOD = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Module");
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setUndecorated(true);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Project :Railway Managment System");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 20, 470, 90);

        lb1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 48)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 255, 255));
        lb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb1.setText("Select Module");
        getContentPane().add(lb1);
        lb1.setBounds(200, 190, 390, 80);

        BTN_STANDARD_USER.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        BTN_STANDARD_USER.setText("Standard User");
        BTN_STANDARD_USER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_STANDARD_USERActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_STANDARD_USER);
        BTN_STANDARD_USER.setBounds(490, 310, 192, 76);

        BTN_ADMIN_MOD.setBackground(new java.awt.Color(255, 255, 255));
        BTN_ADMIN_MOD.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        BTN_ADMIN_MOD.setText("Admin");
        BTN_ADMIN_MOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ADMIN_MODActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_ADMIN_MOD);
        BTN_ADMIN_MOD.setBounds(20, 310, 192, 76);

        BTN_DETAIL_MOD.setBackground(new java.awt.Color(255, 255, 255));
        BTN_DETAIL_MOD.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        BTN_DETAIL_MOD.setText("About US");
        BTN_DETAIL_MOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DETAIL_MODActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_DETAIL_MOD);
        BTN_DETAIL_MOD.setBounds(390, 110, 270, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\Projects\\Railway Managment System(dbms)\\images\\module.png")); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(1024, 1024));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 710, 640);

        setSize(new java.awt.Dimension(712, 640));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_ADMIN_MODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ADMIN_MODActionPerformed
        this.dispose();
        Admin t=new Admin();
        t.setVisible(true);
    }//GEN-LAST:event_BTN_ADMIN_MODActionPerformed

    private void BTN_STANDARD_USERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_STANDARD_USERActionPerformed
       
        setVisible(false);
        Standard_User c=new Standard_User();
        c.setVisible(true);
    }//GEN-LAST:event_BTN_STANDARD_USERActionPerformed

    private void BTN_DETAIL_MODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DETAIL_MODActionPerformed
          JOptionPane.showMessageDialog(null," Project: Railway Managment System \n Design by: Fazila Rubab");
    }//GEN-LAST:event_BTN_DETAIL_MODActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selection_Module.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selection_Module.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selection_Module.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selection_Module.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selection_Module().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_ADMIN_MOD;
    private javax.swing.JButton BTN_DETAIL_MOD;
    private javax.swing.JButton BTN_STANDARD_USER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lb1;
    // End of variables declaration//GEN-END:variables
}
