
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class Standard_User extends javax.swing.JFrame {

    public String name1;
   
    public Standard_User() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));}
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbinfo = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        lbID = new javax.swing.JLabel();
        BTN_REGISTRATION = new javax.swing.JButton();
        BTN_USER_LOGIN = new javax.swing.JButton();
        STANDARD_USER_BACK = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 10, 9));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(null);

        lbinfo.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        lbinfo.setForeground(new java.awt.Color(255, 255, 255));
        lbinfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbinfo.setText("Enter Your Information");
        getContentPane().add(lbinfo);
        lbinfo.setBounds(140, 180, 450, 90);

        lbName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbName.setForeground(new java.awt.Color(255, 255, 255));
        lbName.setText("UserName");
        getContentPane().add(lbName);
        lbName.setBounds(110, 280, 100, 34);
        getContentPane().add(username);
        username.setBounds(260, 280, 235, 34);

        lbID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbID.setForeground(new java.awt.Color(255, 255, 255));
        lbID.setText("Password");
        getContentPane().add(lbID);
        lbID.setBounds(108, 340, 110, 35);

        BTN_REGISTRATION.setBackground(new java.awt.Color(102, 102, 255));
        BTN_REGISTRATION.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BTN_REGISTRATION.setForeground(new java.awt.Color(255, 255, 255));
        BTN_REGISTRATION.setText("Registration");
        BTN_REGISTRATION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_REGISTRATIONActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_REGISTRATION);
        BTN_REGISTRATION.setBounds(10, 530, 220, 50);

        BTN_USER_LOGIN.setBackground(new java.awt.Color(102, 102, 255));
        BTN_USER_LOGIN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BTN_USER_LOGIN.setForeground(new java.awt.Color(255, 255, 255));
        BTN_USER_LOGIN.setText("Login");
        BTN_USER_LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_USER_LOGINActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_USER_LOGIN);
        BTN_USER_LOGIN.setBounds(250, 530, 220, 50);

        STANDARD_USER_BACK.setBackground(new java.awt.Color(102, 102, 255));
        STANDARD_USER_BACK.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        STANDARD_USER_BACK.setForeground(new java.awt.Color(255, 255, 255));
        STANDARD_USER_BACK.setText("BACK");
        STANDARD_USER_BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STANDARD_USER_BACKActionPerformed(evt);
            }
        });
        getContentPane().add(STANDARD_USER_BACK);
        STANDARD_USER_BACK.setBounds(490, 530, 230, 50);

        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        getContentPane().add(pass);
        pass.setBounds(260, 330, 230, 40);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railway pic.jpg"))); // NOI18N
        jLabel2.setText("Registration");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-120, 0, 850, 590);

        setSize(new java.awt.Dimension(721, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_REGISTRATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_REGISTRATIONActionPerformed
this.dispose();
Registration rg=new Registration();
rg.setVisible(true);
        
       /* ClsCandidate s= new ClsCandidate(txtName.getText(),txtID.getText(),gender);
        if(s.InsertStatement()>0)
        {
            JOptionPane.showMessageDialog(null,"Information Save Successfully");
            setVisible(false);
            Quiz_Test test=new Quiz_Test();
            test.setVisible(true);

        }
        else
        JOptionPane.showMessageDialog(null,"Record Not Saved");*/
    }//GEN-LAST:event_BTN_REGISTRATIONActionPerformed

    private void BTN_USER_LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_USER_LOGINActionPerformed
        
        
        
            
            String name=username.getText();
            String password=pass.getText();
          String sql="Select user_name,userpassword from standard_user where user_name ='"+name+"'";
         Connectivity c=new  Connectivity();
         ResultSet r= c.getRs(sql);
         Boolean B=false;
        try {
            while(r.next())
            {
                if(name.equals(r.getString(1))&& password.equals(r.getString(2)))
                {JOptionPane.showMessageDialog(null,"Login Successful");
                 B=true;
                    this.dispose();
                Booking b=new Booking();
                b.setVisible(true);
         String qry="INSERT INTO Recent(username) values('"+name+"')";
              c.ins(qry);
                
                }
            }
                if(B!=true){
                    JOptionPane.showMessageDialog(null,"Login Not Successful");
                }
                   
                
                
                
         
        } catch (SQLException ex) {
            Logger.getLogger(Standard_User.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_BTN_USER_LOGINActionPerformed

    private void STANDARD_USER_BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STANDARD_USER_BACKActionPerformed
        // TODO add your handling code here:

        this.dispose();
        Selection_Module back= new Selection_Module();
        back.setVisible(true);

    }//GEN-LAST:event_STANDARD_USER_BACKActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Standard_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Standard_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Standard_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Standard_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Standard_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_REGISTRATION;
    private javax.swing.JButton BTN_USER_LOGIN;
    private javax.swing.JButton STANDARD_USER_BACK;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbinfo;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
